version: '3'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "transactions:3:1, fraud_alerts:3:1, high_value_transactions:3:1"
    depends_on:
      - zookeeper
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181" ]
      interval: 10s
      timeout: 5s
      retries: 5


  producer_server:
    build: ./producer
    container_name: producer_server
    ports:
      - "5000:5000"
    depends_on:
      kafka:
        condition: service_healthy


  mongo-db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    container_name:
      mongo-db
    volumes:
      - ./mongo-data:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  streams_server:
    build: ./streams
    container_name: streams_server
    ports:
      - "5001:5001"
    depends_on:
      kafka:
        condition: service_healthy
      mongo-db:
        condition: service_healthy




volumes:
  db_data: